humberto@Humbertos-Laptop:~/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02$ python -m pdb charges_calc.py -i source.json -o output.json
> /home/humberto/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02/charges_calc.py(3)<module>()
-> '''
(Pdb) ll
  1  	'''
  2  	Returns total price paid for individual rentals
  3  ->	'''
  4  	import argparse
  5  	import json
  6  	import datetime
  7  	import math
  8  	import logging
  9  	
 10  	log_format = "%(asctime)s %(filename)s:%(lineno)-3d %(levelname)s %(message)s"
 11  	
 12  	log_file = datetime.datetime.now().strftime("%Y-%m-%d") + '.log'
 13  	
 14  	formatter = logging.Formatter(log_format)
 15  	
 16  	file_handler = logging.FileHandler(log_file)
 17  	file_handler.setFormatter(formatter)
 18  	
 19  	logger = logging.getLogger()
 20  	logger.addHandler(file_handler)
 21  	
 22  	
 23  	def parse_cmd_arguments():
 24  	    parser = argparse.ArgumentParser(description='Process some integers.')
 25  	    parser.add_argument('-i', '--input', help='input JSON file', required=True)
 26  	    parser.add_argument('-o', '--output', help='ouput JSON file', required=True)
 27  	
 28  	    return parser.parse_args()
 29  	
 30  	
 31  	def load_rentals_file(filename):
 32  	    with open(filename) as file:
 33  	        try:
 34  	            data = json.load(file)
 35  	        except:
 36  	            exit(0)
 37  	    return data
 38  	
 39  	def calculate_additional_fields(data):
 40  	    for value in data.values():
 41  	        try:
 42  	            rental_start = datetime.datetime.strptime(value['rental_start'], '%m/%d/%y')
 43  	            rental_end = datetime.datetime.strptime(value['rental_end'], '%m/%d/%y')
 44  	            value['total_days'] = (rental_end - rental_start).days
 45  	            value['total_price'] = value['total_days'] * value['price_per_day']
 46  	            value['sqrt_total_price'] = math.sqrt(value['total_price'])
 47  	            value['unit_cost'] = value['total_price'] / value['units_rented']
 48  	        except:
 49  	            exit(0)
 50  	
 51  	    return data
 52  	
 53  	def save_to_json(filename, data):
 54  	    with open(filename, 'w') as file:
 55  	        json.dump(data, file)
 56  	
 57  	if __name__ == "__main__":
 58  	    args = parse_cmd_arguments()
 59  	    data = load_rentals_file(args.input)
 60  	    data = calculate_additional_fields(data)
 61  	    save_to_json(args.output, data)
(Pdb) b28
*** NameError: name 'b28' is not defined
(Pdb) b 28
Breakpoint 1 at /home/humberto/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02/charges_calc.py:28
(Pdb) c
> /home/humberto/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02/charges_calc.py(28)parse_cmd_arguments()
-> return parser.parse_args()
(Pdb) n
--Return--
> /home/humberto/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02/charges_calc.py(28)parse_cmd_arguments()->Namespace(inp...'output.json')
-> return parser.parse_args()
(Pdb) n
> /home/humberto/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02/charges_calc.py(59)<module>()
-> data = load_rentals_file(args.input)
(Pdb) n
> /home/humberto/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02/charges_calc.py(60)<module>()
-> data = calculate_additional_fields(data)
(Pdb) n
SystemExit: 0
> /home/humberto/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02/charges_calc.py(60)<module>()
-> data = calculate_additional_fields(data)
(Pdb) Traceback (most recent call last):
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/home/humberto/anaconda/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/humberto/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02/charges_calc.py", line 60, in <module>
    data = calculate_additional_fields(data)
  File "/home/humberto/anaconda/lib/python3.6/bdb.py", line 54, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/home/humberto/anaconda/lib/python3.6/bdb.py", line 109, in dispatch_exception
    self.user_exception(frame, arg)
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/home/humberto/anaconda/lib/python3.6/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/humberto/anaconda/lib/python3.6/cmd.py(126)cmdloop()
-> line = input(self.prompt)
(Pdb) Traceback (most recent call last):
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/home/humberto/anaconda/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/humberto/Documents/UW_PYTHON/SP_Online_PY220/SP_Python220B_2019/students/humberto_gonzalez/lesson02/charges_calc.py", line 60, in <module>
    data = calculate_additional_fields(data)
  File "/home/humberto/anaconda/lib/python3.6/bdb.py", line 54, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/home/humberto/anaconda/lib/python3.6/bdb.py", line 109, in dispatch_exception
    self.user_exception(frame, arg)
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/home/humberto/anaconda/lib/python3.6/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/humberto/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/humberto/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 1694, in <module>
    pdb.main()
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 1686, in main
    pdb.interaction(None, t)
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/home/humberto/anaconda/lib/python3.6/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/home/humberto/anaconda/lib/python3.6/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.

