{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf200
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;}
{\*\expandedcolortbl;;\csgray\c0;\csgray\c100000;}
\margl1440\margr1440\vieww12600\viewh7800\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs28 \cf0 Chriss-MacBook-Pro:code Gantt$ python charges_calc.py \
usage: charges_calc.py [-h] -i INPUT -o OUTPUT\
charges_calc.py: error: the following arguments are required: -i/--input, -o/--output\
\
\
Chriss-MacBook-Pro:code Gantt$ pylint charges_calc.py \
************* Module charges_calc\
charges_calc.py:22:12: W0621: Redefining name 'data' from outer scope (line 49) (redefined-outer-name)\
charges_calc.py:23:8: W0702: No exception type(s) specified (bare-except)\
charges_calc.py:27:32: W0621: Redefining name 'data' from outer scope (line 49) (redefined-outer-name)\
charges_calc.py:37:8: W0702: No exception type(s) specified (bare-except)\
charges_calc.py:42:27: W0621: Redefining name 'data' from outer scope (line 49) (redefined-outer-name)\
charges_calc.py:48:4: C0103: Constant name "args" doesn't conform to UPPER_CASE naming style (invalid-name)\
charges_calc.py:49:4: C0103: Constant name "data" doesn't conform to UPPER_CASE naming style (invalid-name)\
charges_calc.py:50:4: C0103: Constant name "data" doesn't conform to UPPER_CASE naming style (invalid-name)\
\
~ changing args and data in if__name='__main__' block to ARGS and data eliminates linter suggestions minus \
charges_calc.py:23:8: W0702: No exception type(s) specified (bare-except)\
charges_calc.py:37:8: W0702: No exception type(s) specified (bare-except)\
\
\
\
After running debugger it is clear that the error we see above, finding an input and output, is created at \
def parse_cmd_arguments():\
on the line\
return parser.parse_args()\
\
something might be going wrong in the scripts usage of argparse \
\
might need to be running my command line file with input and output arguments\
\
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0
\cf2 \cb3 \CocoaLigature0 Chriss-MacBook-Pro:code Gantt$ python charges_calc.py -i source.json -o out.json\
\
this might solve that problem, gonna try debugger again to see if i can pass that spot.\
And it did.\
\
\
\
\
Next-\
Worked on adding logging errors. Starting with fixing load_rentals_file() to add an exception with a name, FileNotFoundError.\
\
\
\
Next-\
calculate_additional_fields, error fixing and logging errors.\
\
Traceback (most recent call last):\
  File "charges_calc.py", line 88, in <module>\
    DATA_W_AF = calculate_additional_fields(DATA)\
  File "charges_calc.py", line 63, in calculate_additional_fields\
    value['sqrt_total_price'] = math.sqrt(value['total_price'])\
ValueError: math domain error}